version: "2.2"

services:
  db:
    image: mysql:5
    volumes:
    - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: node-complete
    ports:
      - 3306:3306
    restart: always